config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  root to: redirect('/products')

  resources :products do
  end

  post '/upload_image', to: 'home#upload_image', as: 'upload_image'

  resources :classrooms


  authenticate :user, ->(user) { user.administrator? } do
    resources :administrators, only: [:index] do
      collection do
        post :deposit_all
      end
    end
    resources :classrooms

    post '/administrators/deposit', to: 'administrators#deposit', as: :deposit_administrators
    get '/classroom_management', to: 'administrators#classroom_management', as: 'classroom_management'
    get '/administrator/dashboard', to: 'administrators#dashboard', as: 'admin_dashboard'
    post '/classroom_administrators/add_user', to: 'administrators#add_user_to_classroom', as: 'add_user_to_classroom_administrators'
  end

  resources :investments do
  end

  mount Sidekiq::Web => '/jobs'

  resources :balances, only: [:show] do
    member do
      post 'deposit'
      post 'withdraw'
    end
  end

  resources :transfers, only: [:show, :new, :create] do
    get :confirmation, on: :collection
    post :confirmation, on: :collection
  end

  post '/transfer/confirmation', to: 'transfers#confirmation', as: 'confirmation_transfer'

  resources :users do
    resource :balance, only: [:show] do
      post :deposit
      post :withdraw
    end
    resource :extract, only: [:show]
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  has_many :administrators
  has_many :users

  validates :name, presence: true
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: %i[show edit update destroy]
  before_action :authenticate_administrator!

  def index
    @classrooms = Classroom.all
  end

  def show
    @students = @classroom.users
  end

  def new
    @classroom = Classroom.new
  end

  def edit
  end

  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to classroom_url(@classroom), notice: "Turma criada com sucesso." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to classroom_url(@classroom), notice: "Turma atualizada com sucesso." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @classroom.destroy

    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: "Turma excluída com sucesso." }
    end
  end

  private

  def set_classroom
    @classroom = Classroom.find(params[:id])
  end

  def classroom_params
    params.require(:classroom).permit(:name)
  end

  private

  def authenticate_administrator!
    unless current_user.administrator?
      flash[:alert] = "Acesso negado. Você não é um administrador."
      redirect_to root_path
    end
  end

end

app/views/classrooms/edit.html.erb
<h1 class="text-left mt-20 mb-0" style="color: #DA1B6E; margin-top: 20px; margin-bottom: 40px; font-size: 36px; font-family: 'Arial', sans-serif; text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3); margin-left: 65px;">
  Editar Turma
</h1>

<%= form_with(model: @classroom, url: classroom_path(@classroom), method: :patch, class: "ml-10") do |f| %>
  <div class="mb-4">
    <%= f.label :name, "Nome", style: "color: black; display: block; margin-bottom: 5px;" %>
    <%= f.text_field :name, class: "rounded-md shadow-md text-black" %>
  </div>

  <div class="flex">
    <%= f.submit "Atualizar", class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-pink-600 mr-2" %>
    <%= link_to "Voltar para Turma", classroom_path(@classroom), class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-pink-600 mr-2" %>
    <%= link_to "Voltar para a lista de turmas", classrooms_path, class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-pink-600" %>
  </div>
<% end %>

app/views/classrooms/index.html.erb
<h1>Turmas</h1>

<table class="table-container mx-6">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= link_to classroom.name, classroom_path(classroom) %></td>
        <td>
          <%= link_to "Editar", edit_classroom_path(classroom), class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-pink-600" %>
          <%= link_to "Excluir", classroom_path(classroom), method: :delete, data: { confirm: "Tem certeza que deseja excluir esta turma?" }, class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-pink-600 ml-2" %>
          <%= link_to "Ver Alunos Associados", classroom_path(classroom), class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-pink-600 ml-2" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div style="text-align: right; margin-top: 30px; margin-right: 65px;">
  <%= link_to "Criar Nova Turma", new_classroom_path, class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-pink-600" %>
   <%= link_to "Adicionar aluno à turma", classroom_management_path, class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-pink-600 mr-2" %>
</div>

app/views/classrooms/new.html.erb
<h1 class="text-left mt-20 mb-0" style="color: #DA1B6E; margin-top: 20px; margin-bottom: 40px; font-size: 36px; font-family: 'Arial', sans-serif; text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3); margin-left: 65px;">
  Nova Turma
</h1>

<%= form_with(model: @classroom, url: classrooms_path, class: "ml-10") do |f| %>
  <div class="mb-4">
    <%= f.label :name, "Nome", style: "color: black; display: block; margin-bottom: 5px;" %>
    <%= f.text_field :name, class: "rounded-md shadow-md text-black", style: "border-radius: 5px; box-shadow: 2px 2px 5px hotpink; color: black; margin-bottom: 10px;" %>
  </div>

  <div class="flex">
    <%= f.submit "Criar", class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-pink-600 mr-2" %>
    <%= link_to "Voltar para Lista de Turmas", classrooms_path, class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-pink-600" %>
  </div>
<% end %>

app/views/classrooms/show.html.erb
<h1 class="text-left mt-20 mb-0" style="color: #DA1B6E; margin-top: 20px; margin-bottom: 40px; font-size: 36px; font-family: 'Arial', sans-serif; text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3); margin-left: 65px;">
  Turma: <%= @classroom.name %>
</h1>

<h2 class="text-left mt-4 mb-2 ml-10" style="font-size: 24px; font-family: 'Arial', sans-serif;">
  Alunos
</h2>

<% if @classroom.users.any? %>
  <table class="table-container mx-6 mb-30">
    <thead>
      <tr>
        <th>Nome</th>
      </tr>
    </thead>
    <tbody>
      <% @classroom.users.each do |user| %>
        <tr>
          <td class="text-black"><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="text-black ml-10">Não há alunos nesta turma.</p>
<% end %>

<div class="flex ml-10 mt-4">
  <%= link_to "Editar", edit_classroom_path(@classroom), class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-pink-600 mr-2" %>
  <%= link_to "Adicionar aluno à turma", classroom_management_path, class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-pink-600 mr-2" %>
  <%= link_to "Voltar para Lista de Turmas", classrooms_path, class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-pink-600" %>
</div>