config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  root to: redirect('/products')

  resources :products do
  end

  post '/upload_image', to: 'home#upload_image', as: 'upload_image'

  resources :classrooms


  authenticate :user, ->(user) { user.administrator? } do
    resources :administrators, only: [:index] do
      collection do
        post :deposit_all
      end
    end
    resources :classrooms

    post '/administrators/deposit', to: 'administrators#deposit', as: :deposit_administrators
    get '/classroom_management', to: 'administrators#classroom_management', as: 'classroom_management'
    get '/administrator/dashboard', to: 'administrators#dashboard', as: 'admin_dashboard'
    post '/classroom_administrators/add_user', to: 'administrators#add_user_to_classroom', as: 'add_user_to_classroom_administrators'
  end

  resources :investments do
  end

  mount Sidekiq::Web => '/jobs'

  resources :balances, only: [:show] do
    member do
      post 'deposit'
      post 'withdraw'
    end
  end

  resources :transfers, only: [:show, :new, :create] do
    get :confirmation, on: :collection
    post :confirmation, on: :collection
  end

  post '/transfer/confirmation', to: 'transfers#confirmation', as: 'confirmation_transfer'

  resources :users do
    resource :balance, only: [:show] do
      post :deposit
      post :withdraw
    end
    resource :extract, only: [:show]
  end
end

app/views/shared/_cardsinfo.html.erb
<div class='flex items-center border-b-2 border-white justify-between bg-[#FF6FB5] h-16 p-4 rounded-lg'>
    <div class='text-xs'>
        <b>
            <%= info %>
            <b class='currency-class'>
                <%= value %>
            </b>
        </b>
    </div>
    <% if show_icon %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="3" stroke="red" class="w-6 h-6 cursor-pointer sidebar-eye" onclick="hideCurrency()">
            <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
    <% end %>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= flash_class(key) %>">
    <%= message %>
    <span class="close-btn" onclick="this.parentElement.style.display='none';">&times;</span>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class='w-full h-[10vh] py-4 border-b border-[#FF4398]'>
    <ul class='flex justify-between px-4'>
        <li style="color: <%= current_page?(products_path) ? '#FF4398' : '' %>; border-bottom: <%= current_page?(products_path) ? '1px solid #FF4398' : 'none' %>;" class='text-black font-semibold cursor-pointer transition duration-500 hover:border-b border-[#FF4398] hover:text-[#FF4398]'>
            <%= link_to "Produtos", products_path %>
        </li>
        <li style="color: <%= current_page?(new_investment_path) || current_page?(investments_path) ? '#FF4398' : '' %>; border-bottom: <%= current_page?(new_investment_path) || current_page?(investments_path) ? '1px solid #FF4398' : 'none' %>;" class='text-black font-semibold cursor-pointer transition duration-500 hover:border-b border-[#FF4398] hover:text-[#FF4398]'>
            <%= link_to "Investimentos", investments_path %>
        </li>
        <li style="color: <%= current_page?(new_transfer_path) ? '#FF4398' : '' %>; border-bottom: <%= current_page?(new_transfer_path) ? '1px solid #FF4398' : 'none' %>;" class='text-black font-semibold cursor-pointer transition duration-500 hover:border-b border-[#FF4398] hover:text-[#FF4398]'>
            <%= link_to "Transferência", new_transfer_path %>
        </li>
        <li class='text-black font-semibold cursor-pointer transition duration-500 <%= current_page?(user_extract_path(user_id: current_user.id)) ? "hover:border-b border-[#FF4398] hover:text-[#FF4398]" : "" %>'>
        <%= link_to 'Extrato', user_extract_path(user_id: current_user.id), class: 'hover:no-underline', style: "color: #{current_page?(user_extract_path(user_id: current_user.id)) ? '#FF4398' : ''}; border-bottom: #{current_page?(user_extract_path(user_id: current_user.id)) ? '1px solid #FF4398' : 'none'};" %>
        </li>
        <% if current_user.administrator? %>
            <li class='text-black font-semibold cursor-pointer transition duration-500 hover:border-b border-[#FF4398] hover:text-[#FF4398]'>
                <%= link_to 'Painel', admin_dashboard_path, class: 'hover:no-underline' %>
            </li>
        <% end %>
    </ul>
</nav>

app/views/shared/_icons.html.erb
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 <%= additional_classes %>">
    <path stroke-linecap="round" stroke-linejoin="round" d="<%= path_d %>" />
</svg>

app/views/shared/_page.html.erb
<div class='w-full h-full flex'>
        <aside class='justify-between min-h-screen w-[30vw] p-8 py-6 h-fit flex flex-col bg-[#FF4398]'>
            <nav class='flex items-center gap-4 justify-between'>
                <%= image_tag "https://i.ibb.co/b6wS491/raro-bank-logo.png", class: 'w-36' %>
                <div class='flex gap-2 items-center'>
                    <div class='bg-white w-fit p-[0.5rem] rounded-full text-[#DA1B6E] font-bold'><%= current_user.name.split.first[0] %><%= current_user.name.split.last[0] %></div>
                    <%= render 'shared/icons', additional_classes: "cursor-pointer", path_d: "M16.5 6v.75m0 3v.75m0 3v.75m0 3V18m-9-5.25h5.25M7.5 15h3M3.375 5.25c-.621 0-1.125.504-1.125 1.125v3.026a2.999 2.999 0 010 5.198v3.026c0 .621.504 1.125 1.125 1.125h17.25c.621 0 1.125-.504 1.125-1.125v-3.026a2.999 2.999 0 010-5.198V6.375c0-.621-.504-1.125-1.125-1.125H3.375z" %>

                    <div class='flex cursor-pointer'>
                        <%= render 'shared/icons', additional_classes: "transform rotate-90" , path_d: "M9 8.25H7.5a2.25 2.25 0 00-2.25 2.25v9a2.25 2.25 0 002.25 2.25h9a2.25 2.25 0 002.25-2.25v-9a2.25 2.25 0 00-2.25-2.25H15M9 12l3 3m0 0l3-3m-3 3V2.25" %>
                        <%= button_to "Sair", destroy_user_session_path, method: :delete, data: { turbo_frame: "user-menu" }  %>
                    </div>
                </div>
            </nav>
            <div class='flex flex-col gap-6'>
                <%= render 'shared/cardsinfo', info: 'VALOR ATUAL:', value: number_to_currency(@balance&.current_balance), show_icon: true %>
                <%= render 'shared/cardsinfo', info: 'VALOR DEPOSITADO:', value: number_to_currency(@balance&.balance_deposited), show_icon: false %>
                <%= render 'shared/cardsinfo', info: 'VALOR RETIRADO:', value: number_to_currency(@balance&.withdrawn), show_icon: false %>
                <%= render 'shared/cardsinfo', info: 'TAXA SELIC a.a:', value: "2", show_icon: false %>
            </div>
                <%= render 'shared/components/button', styles: 'bg-[#DA1B6E]' do %>
                  <%= turbo_frame_tag 'transfer-link' do %>
                    <%= link_to "TRANSFERÊNCIA", new_transfer_path, class: "bg-[#DA1B6E] text-white font-bold py-2 px-4 rounded", data: { turbo_frame: 'transfer-link' } %>
                  <% end %>
                <% end %>
        </aside>
        <div class='w-[70vw] min-h-screen h-fit px-2 flex flex-col'>
            <%= render 'shared/header' %>
            <div class='h-[90vh] overflow-y-auto max-h-[90vh] p-8'>
                <%= yield %>
            <div>
        </div>
</div>