config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  root to: redirect('/products')

  resources :products do
  end

  post '/upload_image', to: 'home#upload_image', as: 'upload_image'

  resources :classrooms


  authenticate :user, ->(user) { user.administrator? } do
    resources :administrators, only: [:index] do
      collection do
        post :deposit_all
      end
    end
    resources :classrooms

    post '/administrators/deposit', to: 'administrators#deposit', as: :deposit_administrators
    get '/classroom_management', to: 'administrators#classroom_management', as: 'classroom_management'
    get '/administrator/dashboard', to: 'administrators#dashboard', as: 'admin_dashboard'
    post '/classroom_administrators/add_user', to: 'administrators#add_user_to_classroom', as: 'add_user_to_classroom_administrators'
  end

  resources :investments do
  end

  mount Sidekiq::Web => '/jobs'

  resources :balances, only: [:show] do
    member do
      post 'deposit'
      post 'withdraw'
    end
  end

  resources :transfers, only: [:show, :new, :create] do
    get :confirmation, on: :collection
    post :confirmation, on: :collection
  end

  post '/transfer/confirmation', to: 'transfers#confirmation', as: 'confirmation_transfer'

  resources :users do
    resource :balance, only: [:show] do
      post :deposit
      post :withdraw
    end
    resource :extract, only: [:show]
  end
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  belongs_to :user
  belongs_to :classroom
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    @users = User.all
    @classrooms = Classroom.all

    render 'administrators/dashboard'
  end

  def index
    @users = User.all
    @classrooms = Classroom.all
    @balance = current_user.balance
  end

  def add_user_to_classroom
    @user = User.find_by(id: params[:user_id])
    @classroom = Classroom.find_by(id: params[:classroom_id])

    if @user && @classroom
      @user.update!(classroom: @classroom)
      redirect_to classroom_path(params[:classroom_id]), notice: "Usuário adicionado à turma com sucesso."
    else
      @users = User.all
      @classrooms = Classroom.all
      flash.now[:alert] = "Falha ao adicionar usuário à turma, verifique se todos os campos foram preenchidos."
      render 'administrators/classroom_management'
    end
  end


  def classroom_management
    @classrooms = Classroom.all
    @users = User.all
  end

  def deposit
    @user = User.find(params[:user_id])
    @balance = @user.balance
    amount = params[:amount].to_f

    if @balance && amount.positive?
      @balance.deposit(amount)

      Transfer.create(sender: current_user, receiver: @user, amount: amount)

      redirect_to administrators_path, notice: "Saldo atualizado com sucesso para o usuário."
    else
      redirect_to administrators_path, alert: "Falha ao adicionar saldo. Certifique-se de fornecer um valor positivo."
    end
  end

  def deposit_all
    amount = params[:amount].to_f

    if amount.positive?
      User.all.each do |user|
        balance = user.balance || Balance.new(user: user)
        balance.save! unless balance.persisted?
        balance.deposit(amount)
        Transfer.create(sender: current_user, receiver: user, amount: amount)
      end
      redirect_to administrators_path, notice: "Saldo atualizado com sucesso para todos os usuários."
    else
      redirect_to administrators_path, alert: "Falha ao adicionar saldo. Certifique-se de fornecer um valor positivo."
    end
  end

  private

  def authenticate_administrator!
    unless current_user.administrator?
      flash[:alert] = "Acesso negado. Você não é um administrador."
      redirect_to root_path
    end
  end

end

app/views/administrators/classroom_management.html.erb
<div class="text-left mt-10 mb-0">
  <h2 style="color: #DA1B6E; margin-bottom: 40px; font-size: 36px; font-family: 'Arial', sans-serif; text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3); margin-left: 65px;">
    Adicionar Usuário à Turma
  </h2>

  <%= form_with(url: add_user_to_classroom_administrators_path, method: :post, class: "ml-10") do |f| %>


    <div class="flex mb-4">
      <div class="mr-2">
        <%= f.label :user_id, "Usuário", style: "color: black; display: block; margin-bottom: 5px;" %>
        <%= f.collection_select :user_id, @users, :id, :name, { prompt: "Selecione um usuário" }, style: "border-radius: 5px; box-shadow: 2px 2px 5px hotpink; color: black; margin-bottom: 10px;", selected: nil %>
      </div>

      <div class="ml-2">
        <%= f.label :classroom_id, "Turma", style: "color: black; display: block; margin-bottom: 5px;" %>
        <%= f.collection_select :classroom_id, @classrooms, :id, :name, { prompt: "Selecione uma turma" }, style: "border-radius: 5px; box-shadow: 2px 2px 5px hotpink; color: black; margin-bottom: 10px;", selected: nil %>
      </div>
    </div>

    <%= f.button "Adicionar", class: "bg-pink-500 text-white py-2 px-4 rounded-md shadow-md ml-10 hover:bg-pink-600" %>
  <% end %>
</div>

app/views/administrators/dashboard.html.erb
<div style="text-align: center; margin-top: 50px; margin-bottom: 50px;">
  <h1 style="color: #DA1B6E; margin-bottom: 20px; font-size: 36px; font-family: 'Arial', sans-serif; text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);">Painel Administrativo</h1>

  <div style="display: flex; justify-content: center; align-items: center; gap: 20px;">
    <div>
      <h3 style="color: #DA1B6E; margin-bottom: 10px; font-size: 24px;">Classes</h3>
      <%= link_to "Ver todas as salas de aula", classrooms_path, style: "color: #999; text-decoration: none;" %>
    </div>

    <div style="width: 2px; height: 30px; background-color: #DA1B6E;"></div>

    <div>
      <h3 style="color: #DA1B6E; margin-bottom: 10px; font-size: 24px;">Saldo</h3>
      <%= link_to "Adicionar saldo", administrators_path, style: "color: #999; text-decoration: none;" %>
    </div>

    <div style="width: 2px; height: 30px; background-color: #DA1B6E;"></div>

    <div>
      <h3 style="color: #DA1B6E; margin-bottom: 10px; font-size: 24px;">Produtos</h3>
      <%= link_to "Criar Produto", new_product_path, style: "color: #999; text-decoration: none;" %>
    </div>

  </div>
</div>

app/views/administrators/index.html.erb
<div style="text-align: left; margin-top: 20px; margin-bottom: 0px;">
  <h1 style="color: #DA1B6E; margin-top: 20px; margin-bottom: 40px; font-size: 36px; font-family: 'Arial', sans-serif; text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3); margin-left: 65px;">
    Adicionar saldo
  </h1>

  <div style="display: flex; justify-content: space-between; margin-left: 65px;">
      <%= render 'shared/flash_messages' %>
    <div style=" margin-right: 20px;">
      <%= form_with(url: deposit_administrators_path, method: :post) do |f| %>
        <div style="display: flex; justify-content: flex-start;">
          <div style="text-align: left;">
            <h3 style="color: #DA1B6E; margin-bottom: 10px; margin-left: 65px; font-size: 24px;">Usuário</h3>
            <%= f.collection_select :user_id, @users, :id, :name, { prompt: "Selecione um usuário" }, { style: "border-radius: 5px; box-shadow: 2px 2px 5px hotpink; color: #999; margin-bottom: 20px;"  } %>
            <% f.label :amount, "Valor de depósito", style: "color: #DA1B6E; font-weight: bold;" %>
            <%= f.number_field :amount, step: 0.01, placeholder: "Valor do Depósito", style: "border-radius: 5px; box-shadow: 2px 2px 5px hotpink; color: black; margin-bottom: 20px;" %>
            <%= render 'shared/components/button', styles: 'bg-[#DA1B6E] py-2 px-2' do %>
              <%= f.submit "Depositar" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div style="width: 2px; background-color: #DA1B6E;"></div>

    <div style=" margin-left: 20px;">
      <%= form_with(url: deposit_all_administrators_path, method: :post) do |f| %>
        <div style="display: flex; justify-content: flex-start;">
          <div style="text-align: left; margin-left: 65px;">
            <h3 style="color: #DA1B6E; margin-bottom: 10px; font-size: 24px;">Turma</h3>
            <%= f.collection_select :classroom_id, @classrooms, :id, :name, { prompt: "Selecione uma turma" }, { style: "border-radius: 5px; box-shadow: 2px 2px 5px hotpink; color: #999; margin-bottom: 20px;" } %>
            <% f.label :amount, "Valor de depósito para todos os alunos da turma", style: "color: #999; font-weight: bold;" %>
            <%= f.number_field :amount, step: 0.01, placeholder: "Valor do Depósito", style: "border-radius: 5px; box-shadow: 2px 2px 5px hotpink; color: #999; margin-bottom: 20px;" %>
            <%= render 'shared/components/button', styles: 'bg-[#DA1B6E] py-2 px-2' do %>
              <%= f.submit "Depositar para todos" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>