config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  root to: redirect('/products')

  resources :products do
  end

  post '/upload_image', to: 'home#upload_image', as: 'upload_image'

  resources :classrooms


  authenticate :user, ->(user) { user.administrator? } do
    resources :administrators, only: [:index] do
      collection do
        post :deposit_all
      end
    end
    resources :classrooms

    post '/administrators/deposit', to: 'administrators#deposit', as: :deposit_administrators
    get '/classroom_management', to: 'administrators#classroom_management', as: 'classroom_management'
    get '/administrator/dashboard', to: 'administrators#dashboard', as: 'admin_dashboard'
    post '/classroom_administrators/add_user', to: 'administrators#add_user_to_classroom', as: 'add_user_to_classroom_administrators'
  end

  resources :investments do
  end

  mount Sidekiq::Web => '/jobs'

  resources :balances, only: [:show] do
    member do
      post 'deposit'
      post 'withdraw'
    end
  end

  resources :transfers, only: [:show, :new, :create] do
    get :confirmation, on: :collection
    post :confirmation, on: :collection
  end

  post '/transfer/confirmation', to: 'transfers#confirmation', as: 'confirmation_transfer'

  resources :users do
    resource :balance, only: [:show] do
      post :deposit
      post :withdraw
    end
    resource :extract, only: [:show]
  end
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  enum status: {
    pending: 1,
    confirmed: 2
  }

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :sender, presence: true
  validate :sufficient_balance, if: :sender
  validate :token_not_expired

  before_create :generate_token
  before_create :set_expiration

  def execute_transfer
    sender_balance = sender.balance || Balance.new(user: sender)
    receiver_balance = receiver.balance || Balance.new(user: receiver)

    Transfer.transaction do
      sender_balance.withdraw(amount)
      receiver_balance.deposit(amount)
    end
  end

  def token_expired?
    expires_at.present? && expires_at < Time.current
  end

  private

  def generate_token
    self.token = rand(100000..999999)
  end

  def set_expiration
    self.expires_at = 1.minute.from_now
  end

  def sufficient_balance
    sender_balance = sender.balance || Balance.new(user: sender)
    if amount > sender_balance.current_balance
      errors.add(:amount, "Saldo insuficiente para realizar a transferência.")
    end
  end

  def token_not_expired
    if self.token.present? && token_expired?
      errors.add(:base, "Token expirado!")
    end
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transfer, only: [:show]

  def new
    @transfer = Transfer.new
    @contacts = contacts
  end

  def create
    if within_transfer_hours?
      @transfer = Transfer.new(transfer_params)
      @transfer.sender = current_user
      receiver = find_receiver

      if receiver && !validate_receiver
        if sufficient_balance?(@transfer.amount)
          @transfer.receiver = receiver
          @transfer.status = :pending
          Transfer.transaction do
            @transfer.save!
          end
          TransfersMailer.token_notification(@transfer).deliver_now
          flash[:notice] = "Transferência criada com sucesso."
          redirect_to transfer_path(@transfer)
        else
          flash.now[:alert] = "Saldo insuficiente para realizar a transferência."
          render :new
        end
      else
        @contacts = contacts
        message = validate_receiver ? "Foram inseridos destinatários distintos" : "Destinatário inválido."
        flash.now[:alert] = message
        render :new
      end
    else
      receiver = find_receiver
      @contacts = contacts
      @transfer = Transfer.new(transfer_params)
      @transfer.sender = current_user
      @transfer.receiver = receiver
      @transfer.status = :pending
      Transfer.transaction do
        @transfer.save!
      end
      TransfersMailer.token_notification(@transfer).deliver_now
      redirect_to transfer_path(@transfer)
    end
  end

  def confirmation

    @transfer = Transfer.find_by(token: params[:token])

    if @transfer.present? && (1..5).include?(@transfer.created_at.wday)
      if @transfer.token_expired?
        flash.now[:alert] = "Token expirado!"
        redirect_to new_transfer_path and return
      else
        @transfer.execute_transfer
        @transfer.status = :confirmed
        @transfer.save!
        TransfersMailer.transfer_notification(@transfer).deliver_now
        flash.now[:notice] = "Transferência confirmada com sucesso!"
      end
    elsif @transfer.present? && !(1..5).include?(@transfer.created_at.wday)
      if @transfer.token_expired?
        flash.now[:alert] = "Token expirado!"
        redirect_to new_transfer_path and return
      else
        @transfer.status = :pending
        @transfer.save
        flash.now[:alert] = "Transferencia fora do horario comercial ela sera concluida no dia #{next_transfer_hour}."
      end
    end

    render :confirmation
  end


  def within_transfer_hours?
    current_time = Time.now
    current_time.strftime("%H:%M") >= "08:00" && current_time.strftime("%H:%M") <= "18:00" && (1..5).include?(current_time.wday)
  end

  def next_transfer_hour
    current_time = Time.current
    next_transfer_time = Time.new(current_time.year, current_time.month, current_time.day, 8, 0, 0) + next_transfer_day.days
    next_transfer_time.strftime("%d/%m/%Y às %H:%M")
  end

  def next_transfer_day
    day = Time.current.wday
    if day == 5
      3
    elsif day == 6
      2
    else
      1
    end
  end

  def show
    @transfer = Transfer.find(params[:id])
  end

  private

  def sufficient_balance?(amount)
    current_user.balance.current_balance >= amount
  end

  def transfer_params
    params.require(:transfer).permit(:amount, :status)
  end

  def find_receiver
    if my_contact.present?
      User.find_by(cpf: my_contact)
    else new_contact.present?
      User.find_by(cpf: new_contact)
    end
  end

  def validate_receiver
   my_contact.present? && new_contact.present? && (my_contact != new_contact)
  end

  def my_contact
    params[:transfer][:my_contact_cpf]
  end

  def new_contact
    params[:transfer][:new_contact_cpf]
  end

  def contacts
    current_user.transferable_contacts
  end

  private

  def set_transfer
    @transfer = Transfer.find(params[:id])
    unless @transfer.sender == current_user || @transfer.receiver == current_user
      flash[:alert] = "Acesso não autorizado."
      redirect_to root_path
    end
  end
end

app/views/transfers/confirmation.html.erb
<div style="text-align: left; margin: 0 auto; width: 500px;">
  <% if @transfer.present? %>
    <% if @transfer.token_expired? %>
      <script>
        alert('Token expirado!');
        window.location.href = '<%= new_transfer_path %>';
      </script>
    <% else %>
      <h1>Confirmação de Transferência</h1>
      <%= render 'shared/flash_messages' %>

      <div style="text-align: left; margin: 0 auto; width: 500px;">
        <h1 style="color: black; margin-bottom: 20px; font-size: 24px;">
          <%= @message %>
        </h1>

        <table style="width: 100%; border-collapse: separate; border-spacing: 0 10px;">
          <% if @transfer.sender %>
            <tr>
              <td style="border-radius: 5px; background-color: #DA1B6E; padding: 10px;">
                <h4 style="color: white; margin-bottom: 5px; font-size: 16px;">Remetente:</h4>
                <p style="color: white;"><%= @transfer.sender.name %></p>
              </td>
            </tr>
          <% end %>
          <tr>
            <td style="border-radius: 5px; background-color: #DA1B6E; padding: 10px;">
              <h4 style="color: white; margin-bottom: 5px; font-size: 16px;">Destinatário:</h4>
              <p style="color: white;"><%= @transfer.receiver.name %></p>
            </td>
          </tr>
          <tr>
            <td style="border-radius: 5px; background-color: #DA1B6E; padding: 10px;">
              <h4 style="color: white; margin-bottom: 5px; font-size: 16px;">Valor:</h4>
              <p style="color: white;"><%= number_to_currency(@transfer.amount) %></p>
            </td>
          </tr>
        </table>

        <div style="text-align: center; margin-top: 30px;">
          <%= link_to "Voltar para a lista de transferências", new_transfer_path, style: "color: #DA1B6E; font-size: 16px; text-decoration: none; display: inline-block; padding: 8px 16px; border-radius: 5px; background-color: #EEE; box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);" %>
        </div>
      </div>
    <% end %>
  <% else %>
    <h1>Confirmação de Transferência</h1>
    <%= render 'shared/flash_messages' %>

    <div style="text-align: left; margin: 0 auto; width: 500px;">
      <h1 style="color: black; margin-bottom: 20px; font-size: 24px;">
        <%= @message %>
      </h1>

      <table style="width: 100%; border-collapse: separate; border-spacing: 0 10px;">
        <tr>
          <td style="border-radius: 5px; background-color: #DA1B6E; padding: 10px;">
            <h4 style="color: white; margin-bottom: 5px; font-size: 16px;">Token:</h4>
            <p class="error-message"><%= @message %></p>
          </td>
        </tr>
      </table>

      <div style="text-align: center; margin-top: 30px;">
        <a href="<%= request.referrer || new_transfer_path %>" style="color: #DA1B6E; font-size: 16px; text-decoration: none; display: inline-block; padding: 8px 16px; border-radius: 5px; background-color: #EEE; box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);">Tentar Novamente</a>
      </div>
    </div>
  <% end %>
</div>

app/views/transfers/new.html.erb
<div style="text-align: left; margin-top: 20px; margin-bottom: 0px;">
  <h1 style="color: #DA1B6E; margin-top: 20px; margin-bottom: 40px; font-size: 36px; font-family: 'Arial', sans-serif; text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3); margin-left: 65px;">
    Nova Transferência
  </h1>

  <%= form_with(model: @transfer, url: transfers_path) do |form| %>

    <div style="display: flex; justify-content: flex-start;">
      <% if @contacts.present? %>
          <div style="text-align: left; margin-right: 20px;">
            <h3 style="color: #DA1B6E; margin-bottom: 10px; margin-left: 65px; font-size: 24px;">Meus contatos</h3>
            <%= form.label :my_contact_cpf, "Contato" %>
            <%= form.collection_select :my_contact_cpf, @contacts, :cpf, :name, { prompt: "Selecione um contato" }, { style: "border-radius: 5px; box-shadow: 2px 2px 5px hotpink; color: #999; margin-bottom: 20px;" } %>
          </div>
      <% end %>
    </div>

    <div style="text-align: left; margin-left: 65px;">
      <hr style="border: none; border-top: 2px solid #DA1B6E; margin-bottom: 10px; margin-right: 60px;">
      <h3 style="color: #DA1B6E; margin-bottom: 10px; font-size: 24px;">Novo contato</h3>
      <div style="display: flex; margin-bottom: 10px;">
        <div style="margin-right: 10px;">
          <h4 style="color: black; margin-bottom: 5px; font-size: 16px;">CPF do Destinatário</h4>
          <%= form.text_field :new_contact_cpf, placeholder: "CPF do destinatário", style: "border-radius: 5px; box-shadow: 2px 2px 5px hotpink; color: black;" %>
          <% if @transfer.errors[:receiver_cpf].any? %>
            <div style="color: red; margin-left: 65px;">
              <% @transfer.errors[:receiver_cpf].each do |error| %>
                <p><%= error %></p>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>


    <div style="text-align: left; margin-left: 65px;">
      <hr style="border: none; border-top: 2px solid #DA1B6E; margin-bottom: 20px; margin-right: 60px;">
      <%= form.label :amount, "Valor da Transferência", style: "color: black; display: block; margin-bottom: 5px;" %>
      <%= form.number_field :amount, step: 0.01, placeholder: "Paulo$", style: "border-radius: 5px; box-shadow: 2px 2px 5px hotpink; color: black; margin-bottom: 10px;" %>
      <% if @transfer.errors[:amount].any? %>
        <div style="color: red; margin-left: 65px;">
          <% @transfer.errors[:amount].each do |error| %>
            <p><%= error %></p>
          <% end %>
        </div>
      <% end %>
    </div>

    <div style="text-align: right; margin-top: 20px; margin-right: 60px;">
      <%= render 'shared/components/button', styles: 'bg-[#DA1B6E] py-2 px-4' do %>
        <%= form.submit "Iniciar Transferência" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/transfers/show.html.erb
<div style="text-align: center; margin-top: 30px; background-color: #F8F8F8; border-radius: 5px; padding: 20px; box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3); margin-bottom: 20px; margin-left: 100px; margin-right: 100px;">
  <h1 style="color: #DA1B6E; margin-bottom: 40px; font-size: 36px; font-family: 'Arial', sans-serif; text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);">
    Confirmação de Transferência
  </h1>

  <div style="text-align: left; margin: 0 auto; width: 500px;">
      <%= render 'shared/flash_messages' %>

    <table style="width: 100%; border-collapse: separate; border-spacing: 0 10px;">
      <tr>
        <td style="border-radius: 5px; background-color: #DA1B6E; padding: 10px;">
          <h4 style="color: white; margin-bottom: 5px; font-size: 16px;">Remetente:</h4>
          <p style="color: white;"><%= @transfer.sender.name %></p>
        </td>
      </tr>
      <tr>
        <td style="border-radius: 5px; background-color: #DA1B6E; padding: 10px;">
          <h4 style="color: white; margin-bottom: 5px; font-size: 16px;">Destinatário:</h4>
          <p style="color: white;"><%= @transfer.receiver.name %></p>
        </td>
      </tr>
      <tr>
        <td style="border-radius: 5px; background-color: #DA1B6E; padding: 10px;">
          <h4 style="color: white; margin-bottom: 5px; font-size: 16px;">Valor:</h4>
          <p style="color: white;"><%= number_to_currency(@transfer.amount) %></p>
        </td>
      </tr>
    </table>

    <%= form_tag(confirmation_transfers_path, method: :get, enforce_utf8: false) do |form| %>
      <div style="display: flex; align-items: center; justify-content: center; margin-top: 30px;">
        <div style="flex: 1; text-align: center;">
          <h4 style="color: black; margin-bottom: 5px; font-size: 16px;">Token de confirmação</h4>
          <%= text_field_tag :token, nil, style: "border-radius: 5px; box-shadow: 2px 2px 5px hotpink; color: black;" %>
        </div>
        <div style="flex: 1; text-align: center;">
          <%= render 'shared/components/button', styles: 'bg-[#DA1B6E] py-2 px-4' do %>
            <%= submit_tag "Confirmar Transferência" %>
          <% end %>
        </div>
      </div>
    <% end %>


    <div style="text-align: center; margin-top: 30px;">
      <%= link_to "Voltar para a lista de transferências", new_transfer_path, style: "color: #DA1B6E; font-size: 16px; text-decoration: none; display: inline-block; padding: 8px 16px; border-radius: 5px; background-color: #EEE; box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);" %>
    </div>
  </div>
</div>